main: plugin.xfy9326.mutualchat.telegram.MainPlugin

name: MutualChat_Telegram
version: 0.4
author: XFY9326
description: Chat between Minecraft Server and Telegram
website: https://www.xfy9326.top/?p=21

commands:
  sendposition:
    description: Send position to telegram